---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a VPC, with 3 subnets (Management, client, server) for 2 Availability Zones.
  It deploys an Internet Gateway, with a default  route on the public subnets.
  This template also creates a HA pair across Availability Zones with two instance of Citrix ADC:
  3 ENIs associated to 3 VPC subnets (Management, Client, Server) on primary and 3 ENIs associated
  to 3 VPC subnets (Management, Client, Server) on secondary.
  All the resource names created by this CFT will be prefixed with a tagName of the stackname
  **WARNING** This template creates AWS resources.
  You will be billed for the AWS resources used if you create a stack from this template."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Availability Zone configuration
        Parameters:
          - PrimaryAvailabilityZone
          - SecondaryAvailabilityZone

      - Label:
          default: Network configuration
        Parameters:
          - VPCCIDR
          - RestrictedWebAppCIDR
          - RestrictedSSHCIDR
          - PrimaryManagementPrivateSubnetCIDR
          - PrimaryClientPublicSubnetCIDR
          - PrimaryServerPrivateSubnetCIDR
          - SecondaryManagementPrivateSubnetCIDR
          - SecondaryClientPublicSubnetCIDR
          - SecondaryServerPrivateSubnetCIDR
          - PrimaryManagementPrivateIP
          - PrimaryClientPrivateIP
          - PrimaryServerPrivateIP
          - SecondaryManagementPrivateIP
          - SecondaryClientPrivateIP
          - SecondaryServerPrivateIP
          - VPCTenancy

      - Label:
          default: Bastion host configuration
        Parameters:
          - NumBastionHosts

      - Label:
          default: Citrix ADC configuration
        Parameters:
          - CitrixADCImageID
          - KeyPairName
          - CitrixADCInstanceType

    ParameterLabels:
      CitrixADCImageID:
        default: Citrix ADC AMI ID

      VPCCIDR:
        default: VPC CIDR

      PrimaryAvailabilityZone:
        default: Primary Availability Zone
      PrimaryManagementPrivateSubnetCIDR:
        default: Primary Management Private Subnet CIDR
      PrimaryClientPublicSubnetCIDR:
        default: Primary Client Public Subnet CIDR
      PrimaryServerPrivateSubnetCIDR:
        default: Primary Server Private Subnet CIDR

      SecondaryAvailabilityZone:
        default: Secondary Availability Zone
      SecondaryManagementPrivateSubnetCIDR:
        default: Secondary Management Private Subnet CIDR
      SecondaryClientPublicSubnetCIDR:
        default: Secondary Client Public Subnet CIDR
      SecondaryServerPrivateSubnetCIDR:
        default: Secondary Server Private Subnet CIDR

      PrimaryManagementPrivateIP:
        default: Primary Management Private IP
      PrimaryClientPrivateIP:
        default: Primary Client Private IP
      PrimaryServerPrivateIP:
        default: Primary Server Private IP
      SecondaryManagementPrivateIP:
        default: Secondary Management Private IP
      SecondaryClientPrivateIP:
        default: Secondary Client Private IP
      SecondaryServerPrivateIP:
        default: Secondary Server Private IP

      VPCTenancy:
        default: VPC tenancy attribute
      RestrictedWebAppCIDR:
        default: Remote web traffic CIDR
      RestrictedSSHCIDR:
        default: Remote ssh traffic CIDR
      KeyPairName:
        default: Key pair name
      CitrixADCInstanceType:
        default: Citrix ADC instance type

Parameters:
  NumBastionHosts:
    AllowedValues:
      - '1'
      - '2'
    Default: '1'
    Description: The number of bastion hosts to create. The maximum number is two.
    Type: String
  CitrixADCImageID:
    Type: String
    Default: ""
    Description: >-
      [OPTIONAL] AMI ID of Citrix ADC to be provisioned. If left empty, "Citrix ADC VPX - Customer Licensed Version 13.0-41.20
      (https://aws.amazon.com/marketplace/pp/B00AA01BOE)" is provisioned by default
  VPCCIDR:
    Description: CIDR Block for VPC
    Type: String
    Default: 10.0.0.0/16
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  VPCTenancy:
    Description: The allowed tenancy of instances launched into the VPC
    Type: String
    Default: default
    AllowedValues:
      - default
      - dedicated
  PrimaryAvailabilityZone:
    Description: Availability Zone for Primary CitrixADC deployment
    Type: AWS::EC2::AvailabilityZone::Name
  SecondaryAvailabilityZone:
    Description: Availability Zone for Secondary CitrixADC deployment
    Type: AWS::EC2::AvailabilityZone::Name
  PrimaryManagementPrivateSubnetCIDR:
    Description: CIDR block for primary management private subnet located in the primary Availability Zone
    Type: String
    Default: 10.0.1.0/24
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  PrimaryClientPublicSubnetCIDR:
    Description: CIDR block for primary client public subnet located in the primary Availability Zone
    Type: String
    Default: 10.0.2.0/24
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  PrimaryServerPrivateSubnetCIDR:
    Description: CIDR block for primary server private subnet located in the primary Availability Zone
    Type: String
    Default: 10.0.3.0/24
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  SecondaryManagementPrivateSubnetCIDR:
    Description: CIDR block for secondary management private subnet located in the secondary Availability Zone
    Type: String
    Default: 10.0.4.0/24
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  SecondaryClientPublicSubnetCIDR:
    Description: CIDR block for secondary client public subnet located in the secondary Availability Zone
    Type: String
    Default: 10.0.5.0/24
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  SecondaryServerPrivateSubnetCIDR:
    Description: CIDR block for secondary server private subnet located in the secondary Availability Zone
    Type: String
    Default: 10.0.6.0/24
    MinLength: 9
    MaxLength: 18
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  PrimaryManagementPrivateIP:
    Default: ""
    Type: String
    Description: >-
      [OPTIONAL] Leave empty for automatic assignment. Private IP assigned to the Primary Management ENI (last octet has to be between 5 and 254).
  PrimaryClientPrivateIP:
    Default: ""
    Type: String
    Description: >-
      [OPTIONAL] Leave empty for automatic assignment. Private IP assigned to the Primary Client ENI (last octet has to be between 5 and 254).
  PrimaryServerPrivateIP:
    Default: ""
    Type: String
    Description: >-
      [OPTIONAL] Leave empty for automatic assignment. Private IP assigned to the Primary Server ENI (last octet has to be between 5 and 254).
  SecondaryManagementPrivateIP:
    Default: ""
    Type: String
    Description: >-
      [OPTIONAL] Leave empty for automatic assignment. Private IP assigned to the Secondary Management ENI (last octet has to be between 5 and 254).
  SecondaryClientPrivateIP:
    Default: ""
    Type: String
    Description: >-
      [OPTIONAL] Leave empty for automatic assignment. Private IP assigned to the Secondary Client ENI (last octet has to be between 5 and 254).
  SecondaryServerPrivateIP:
    Default: ""
    Type: String
    Description: >-
      [OPTIONAL] Leave empty for automatic assignment. Private IP assigned to the Secondary Server ENI (last octet has to be between 5 and 254).
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. This bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-), but should
      not start or end with a hyphen. You can specify your own bucket if you
      copy all of the assets and submodules into it, if you want to override the
      Quick Start behavior for your specific implementation.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-citrix-adc-ha-across-az/
    Description: >-
      [Note] The QSS3KeyPrefix should have to end with forward slash (/).
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RestrictedWebAppCIDR:
    Type: String
    MinLength: 9
    MaxLength: 18
    Description:
      "A CIDR block that is allowed to access the ADC on tcp ports 80, 443.
      We recommend that you use a constrained CIDR range to
      reduce the potential of inbound attacks from unknown IP addresses."
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  RestrictedSSHCIDR:
    Type: String
    MinLength: 9
    MaxLength: 18
    Description:
      "A CIDR block that is allowed to access the bastion host on port 22.
      We recommend that you use a constrained CIDR range to
      reduce the potential of inbound attacks from unknown IP addresses."
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  KeyPairName:
    ConstraintDescription: "Can contain only alphanumeric characters, spaces, dashes and underscores."
    Description: EC2 key pair name to remotely access ADCs on port 22 (SSH)
    MinLength: 1
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    MaxLength: 64
    Type: AWS::EC2::KeyPair::KeyName
  CitrixADCInstanceType:
    Default: m4.xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
    Type: String
    Description: Citrix ADC instance type
    AllowedValues:
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge

Conditions:
  2BastionCondition: !Equals
    - !Ref NumBastionHosts
    - '2'

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
      Parameters:
        NumberOfAZs: '2'
        AvailabilityZones: !Join 
          - ','
          - - !Ref PrimaryAvailabilityZone
            - !Ref SecondaryAvailabilityZone
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1CIDR: !Ref PrimaryClientPublicSubnetCIDR
        PublicSubnet2CIDR: !Ref SecondaryClientPublicSubnetCIDR
        CreatePrivateSubnets: "true"
        PrivateSubnet1ACIDR: !Ref PrimaryServerPrivateSubnetCIDR
        PrivateSubnet2ACIDR: !Ref SecondaryServerPrivateSubnetCIDR
        CreateAdditionalPrivateSubnets: "true"
        PrivateSubnet1BCIDR: !Ref PrimaryManagementPrivateSubnetCIDR
        PrivateSubnet2BCIDR: !Ref SecondaryManagementPrivateSubnetCIDR
        VPCTenancy: !Ref VPCTenancy

  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template
      Parameters:
        BastionAMIOS: Ubuntu-Server-16.04-LTS-HVM
        KeyPairName: !Ref KeyPairName
        NumBastionHosts: !Ref NumBastionHosts
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}submodules/quickstart-linux-bastion/
        RemoteAccessCIDR: !Ref RestrictedSSHCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID

  WorkLoadStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/citrix-adc-ha-across-az-workload.template.yaml
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        VPCTenancy: !Ref VPCTenancy
        VPCCIDR: !Ref VPCCIDR
        RestrictedWebAppCIDR: !Ref RestrictedWebAppCIDR
        PrimaryManagementPrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet1BID
        PrimaryClientPublicSubnetID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PrimaryServerPrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        SecondaryManagementPrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet2BID
        SecondaryClientPublicSubnetID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        SecondaryServerPrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        PrimaryManagementPrivateIP: !Ref PrimaryManagementPrivateIP
        PrimaryClientPrivateIP: !Ref PrimaryClientPrivateIP
        PrimaryServerPrivateIP: !Ref PrimaryServerPrivateIP
        SecondaryManagementPrivateIP: !Ref SecondaryManagementPrivateIP
        SecondaryClientPrivateIP: !Ref SecondaryClientPrivateIP
        SecondaryServerPrivateIP: !Ref SecondaryServerPrivateIP
        CitrixADCImageID: !Ref CitrixADCImageID
        KeyPairName: !Ref KeyPairName
        CitrixADCInstanceType: !Ref CitrixADCInstanceType
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix



Outputs:
  VPCID:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCID
  PrimaryManagementPrivateSubnetID:
    Description: Primary Management Private Subnet ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1BID
  PrimaryClientPublicSubnetID:
    Description: Primary Client Public Subnet ID
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1ID
  PrimaryServerPrivateSubnetID:
    Description: Primary Server Private Subnet ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
  SecondaryManagementPrivateSubnetID:
    Description: Secondary Management Private Subnet ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2BID
  SecondaryClientPublicSubnetID:
    Description: Secondary Client Public Subnet ID
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2ID
  SecondaryServerPrivateSubnetID:
    Description: Secondary Server Private Subnet ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
  SecurityGroupID:
    Description: Security Group ID for ADC ENIs
    Value: !GetAtt WorkLoadStack.Outputs.SecurityGroupID
  InstanceProfileName:
    Description: Instance Profile for ADCs
    Value: !GetAtt WorkLoadStack.Outputs.InstanceProfileName
  PrimaryADCInstanceID:
    Description: Primary ADC Instance ID
    Value: !GetAtt WorkLoadStack.Outputs.PrimaryADCInstanceID
  PrimaryManagementPrivateNSIP:
    Description: Primary Management Private NSIP
    Value: !GetAtt WorkLoadStack.Outputs.PrimaryManagementPrivateNSIP
  PrimaryClientPublicEIP:
    Description: Primary Client Public EIP
    Value: !GetAtt WorkLoadStack.Outputs.PrimaryClientPublicEIP
  PrimaryClientPrivateVIP:
    Description: Primary Client Private VIP
    Value: !GetAtt WorkLoadStack.Outputs.PrimaryClientPrivateVIP
  SecondaryADCInstanceID:
    Description: Secondary ADC Instance ID
    Value: !GetAtt WorkLoadStack.Outputs.SecondaryADCInstanceID
  SecondaryManagementPrivateNSIP:
    Description: Secondary Management Private NSIP
    Value: !GetAtt WorkLoadStack.Outputs.SecondaryManagementPrivateNSIP
  SecondaryClientPrivateVIP:
    Description: Secondary Client Private VIP
    Value: !GetAtt WorkLoadStack.Outputs.SecondaryClientPrivateVIP
  LinuxBastionHostEIP1:
    Description: Elastic IP 1 for Bastion
    Value: !GetAtt BastionStack.Outputs.EIP1
  LinuxBastionHostEIP2:
    Condition: 2BastionCondition
    Description: Elastic IP 2 for Bastion
    Value: !GetAtt BastionStack.Outputs.EIP2
